filebeat.inputs:
- input_type: log
  enable: true
  # the path to save logs
  paths:
   - /usr/share/filebeat/log/**
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
  multiline.timeout: 10s
  tags: ["pre-logs"]
  # the location to save restore record infomation
  registry_file: /usr/share/filebeat/data/
  fields:
    logsource: node1
    logtype: pre

output.logstash:
  enabled: true
  # the host and port filebeat export to
  hosts: ["logstash:5045"]
  